export type GameId="gomoku"|"reversi"|"connect4"|"tictactoe";
export type Cell="human"|"jev"|null;
export type State={board:Cell[][];turn:"human"|"jev"};
export type Move={row:number;col:number;label:string;score:number;reason:string};
const dirs=[-1,0,1].flatMap(dr=>[-1,0,1].map(dc=>[dr,dc] as const)).filter(([a,b])=>a||b);
const tag=(r:number,c:number)=>`${String.fromCharCode(65+c)}${r+1}`;
const copy=(b:Cell[][])=>b.map(r=>[...r]);
export const config={gomoku:{name:"五子棋",rows:15,cols:15},reversi:{name:"黑白棋",rows:8,cols:8},connect4:{name:"四子棋",rows:6,cols:7},tictactoe:{name:"井字棋",rows:3,cols:3}} as const;
export function initial(id:GameId):State{const g=config[id],board=Array.from({length:g.rows},()=>Array<Cell>(g.cols).fill(null));if(id==="reversi"){board[3][3]=board[4][4]="jev";board[3][4]=board[4][3]="human"}return{board,turn:"human"}}
function lineWin(b:Cell[][],p:Cell,n:number){for(let r=0;r<b.length;r++)for(let c=0;c<b[0].length;c++)for(const[d,e]of[[1,0],[0,1],[1,1],[1,-1]])if(Array.from({length:n},(_,i)=>b[r+d*i]?.[c+e*i]).every(x=>x===p))return true;return false}
function flips(b:Cell[][],r:number,c:number,p:"human"|"jev"){if(b[r]?.[c])return[] as[number,number][];const o=p==="human"?"jev":"human",all:[number,number][]=[];for(const[dr,dc]of dirs){const one:[number,number][]=[];let x=r+dr,y=c+dc;while(b[x]?.[y]===o){one.push([x,y]);x+=dr;y+=dc}if(one.length&&b[x]?.[y]===p)all.push(...one)}return all}
export function moves(id:GameId,s:State,p=s.turn):Move[]{const b=s.board,out:Move[]=[];if(id==="connect4"){b[0].forEach((x,c)=>{if(x)return;let r=b.length-1;while(b[r][c])r--;const n=copy(b);n[r][c]=p;out.push({row:r,col:c,label:tag(r,c),score:lineWin(n,p,4)?1e6:100-Math.abs(3-c)*12,reason:lineWin(n,p,4)?"立即四连":"控制高价值列"})});return out}b.forEach((row,r)=>row.forEach((x,c)=>{if(x)return;if(id==="reversi"){const f=flips(b,r,c,p);if(!f.length)return;const corner=(r===0||r===7)&&(c===0||c===7);out.push({row:r,col:c,label:tag(r,c),score:f.length*30+(corner?1200:0),reason:`翻转${f.length}子${corner?"并占稳定角":""}`})}else{const n=copy(b);n[r][c]=p;const win=lineWin(n,p,id==="gomoku"?5:3);const center=20-Math.abs(r-(b.length-1)/2)-Math.abs(c-(b[0].length-1)/2);out.push({row:r,col:c,label:tag(r,c),score:win?1e6:center*4,reason:win?"立即连线获胜":"中心与连线潜力"})}}));return out}
export function apply(id:GameId,s:State,m:Pick<Move,"row"|"col">):State{const b=copy(s.board);if(id==="reversi")for(const[r,c]of flips(b,m.row,m.col,s.turn))b[r][c]=s.turn;b[m.row][m.col]=s.turn;return{board:b,turn:s.turn==="human"?"jev":"human"}}
export function outcome(id:GameId,s:State):"human"|"jev"|"draw"|null{const n=id==="gomoku"?5:id==="connect4"?4:3;if(id!=="reversi"){if(lineWin(s.board,"human",n))return"human";if(lineWin(s.board,"jev",n))return"jev";return s.board.every(r=>r.every(Boolean))?"draw":null}if(moves(id,s,"human").length||moves(id,s,"jev").length)return null;const h=s.board.flat().filter(x=>x==="human").length,j=s.board.flat().filter(x=>x==="jev").length;return h===j?"draw":h>j?"human":"jev"}
